await Country.insertMany([
  {
    name: "Seoul",
    country: "South Korea",
    continent: "Asia",
    population: 25,
  },
  { name: "Mumbai", country: "India", continent: "Asia", population: 19 },
  {
    name: "Lagos",
    country: "Nigeria",
    continent: "Africa",
    population: 13,
  },
  {
    name: "Beijing",
    country: "China",
    continent: "Asia",
    population: 19,
  },
  {
    name: "Shanghai",
    country: "China",
    continent: "Asia",
    population: 25,
  },
  { name: "Osaka", country: "Japan", continent: "Asia", population: 19 },
  {
    name: "Cairo",
    country: "Egypt",
    continent: "Africa",
    population: 20,
  },
  { name: "Tokyo", country: "Japan", continent: "Asia", population: 37 },
  {
    name: "Karachi",
    country: "Pakistan",
    continent: "Asia",
    population: 15,
  },
  {
    name: "Dhaka",
    country: "Bangladesh",
    continent: "Asia",
    population: 19,
  },
  {
    name: "Rio de Janeiro",
    country: "Brazil",
    continent: "South America",
    population: 13,
  },
  {
    name: "São Paulo",
    country: "Brazil",
    continent: "South America",
    population: 21,
  },
  {
    name: "Mexico City",
    country: "Mexico",
    continent: "North America",
    population: 21,
  },
  { name: "Delhi", country: "India", continent: "Asia", population: 28 },
  {
    name: "Buenos Aires",
    country: "Argentina",
    continent: "South America",
    population: 14,
  },
  {
    name: "Kolkata",
    country: "India",
    continent: "Asia",
    population: 14,
  },
  {
    name: "New York",
    country: "United States",
    continent: "North America",
    population: 18,
  },
  {
    name: "Manila",
    country: "Philippines",
    continent: "Asia",
    population: 13,
  },
  {
    name: "Chongqing",
    country: "China",
    continent: "Asia",
    population: 14,
  },
  {
    name: "Istanbul",
    country: "Turkey",
    continent: "Europe",
    population: 14,
  },
]);
